### ISSUE TITLE
[bug] UnknownRpcError

### ISSUE THREAD

**Issue by vanyasav** [reown-com/appkit#4144]
### Link to minimal reproducible example

https://github.com/vanyasav/angular-reown-wagmi/tree/rpc_error

### Summary

In the latest versions of appkit when trying to connect to [Immutable zkEVM](https://www.immutable.com/products/immutable-zkevm) this error pops up:

```
ERROR UnknownRpcError: An unknown RPC error occurred.

Details: transports[i] is not a function
Version: viem@2.25.0
    at rejected (chunk-JJNT44DE.js?v=a0f989d3:86:29)
Caused by: TypeError: transports[i] is not a function
    at chunk-JJNT44DE.js?v=a0f989d3:92:61
    at __async (chunk-JJNT44DE.js?v=a0f989d3:76:10)
    at chunk-JJNT44DE.js?v=a0f989d3:92:61
```

https://github.com/user-attachments/assets/c4f95499-921b-4698-8e72-4d6431315632

Works fine in 1.6.4

### List of related npm package versions

    "@reown/appkit": "^1.7.2",
    "@reown/appkit-adapter-wagmi": "^1.7.2",
    "viem": "^2.25.0",
    "wagmi": "^2.14.16",

### Node.js Version

20.13.1

### Package Manager

10.5.2

**Comment by layinka** [comment]
+1 on this

**Comment by prakhar728** [comment]
I got the same error.

**Comment by metatxn** [comment]
@vanyasav @prakhar728  below config worked for me. explicitly added transport config.

```
const wagmiAdapter = new WagmiAdapter({
  networks: chains,
  projectId,
  ssr: false,
  storage: createStorage({
    storage: cookieStorage,
  }),
  // Add explicit http transport configuration
  transports: {
    [lensChains.id]: http(),
    [optimism.id]: http(),
    [optimismSepolia.id]: http(),
  },
})
```
